README.md
https://www.youtube.com/cursodepython
=> /CursoDePython

README.md
Adicionando Curso em video a lista
=> Curso em video

README.md
Rodrigo Branas
Canal dotNET
Python para Zumbis
TekZoom
Glaucia Lemos
=> Adição de novos canais

README.md
Adicionar o Canal Portal Programando
=> Add Portal Programando

README.md
=> Adicionando mais alguns canais brasucas

README.md
Adiciona os seguintes canais:
- PHPSP
- Pagar.me Talks
- Filipe Deschamps
=> Adiciona novos canais

README.md
2ª pull request, se não estiver de acordo é só falar. =D
Foi adicionado o canal **eXcript** e corrigido o conflito de merge.
=> Adicionado canal eXcript

README.md
=> Add Canal ML4U

README.md
Comunidade que eu sou gerente, junto com outras pessoas e também meu canal pessoal no youtube.
=> Canais Caqui Coders e Claudiney Junior

README.md
Retirei o "=====" na linha 76 :+1:
=> Consertando linha 76

README.md
+ **Adição** de dois novos canais
+ **Alteração** de canal já existente duplicado
=> Update no README.md

README.md
Está aqui meu Canal, muito obrigado! :)
=> Canal Escola-FrontEnd

README.md
Adicionando Python Café e Vida Programação
=> Adicionando mais dois canais

README.md
Adicionando um novo canal para a lista.
=> Adicionado Canal Patrick Monteiro - Quasar Framework

README.md
Canal foco em desenvolvimento de jogos e monetização. Traz um conteúdo bem legal para quem deseja conhecer mais a área, principalmente se você for iniciante.
Trarei mais alguns canais com excelente qualidade relacionados ao desenvolvimento de jogos.
=> Adicionado canal do Davifo

README.md
Adicionado novo canal:
* DevNaEstrada
=> Adicionado canal DevNaEstrada

conteudos/big-data.md, conteudos/desenvolvimento-back-end.md, conteudos/desenvolvimento-front-end.md, conteudos/entrevistas-webinars-e-dicas.md, conteudos/inteligencia-artificial.md, conteudos/podcasts.md, conteudos/seguranca.md
Alguns itens da lista não estavam padronizados, corrigi isso em um commit. No outro adicionei o canal WoMakersCode.
=> Adicionando WoMakersCode

README.md
=> Adiciona Canal 201 Front-End

README.md
**Tenha certeza que os items abaixo foram revisados, antes de enviar o Pull request:**
=> Add canal balta.io

README.md
**Tenha certeza que os items abaixo foram revisados, antes de enviar o Pull request:**
=> Corrigindo link para seção de games

README.md
=> Adicionado canal Fábrica de código [Atualizado]

README.md
=> Adiciona canal Thiago Aguiar(Atualizado)

README.md
Adicionando minhas principais referências de Cloud e DevOps (E um nodezinho)
=> Canais de cloud & devops

README.md
=> Adicionado o canal PRX 3D - Praxinoscopio

README.md
=> Arruma nome do Professor Rodrigo Mello

README.md
=> Adiciona o canal Universo Programado

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, README.md, readme_checker_test.rb
Agora aceitamos qualquer tipo de conteúdo em video, não somente conteúdo do Youtube.
=> Ampliando o escopo do repo para aceitar qualquer tipo de conteúdo em vídeo

README.md
Adicionando o canal do Curso de Python e Flask com Bruno Rocha
=> Adicionando o canal Bruno Rocha - Python e Flask

README.md
=> Adiciona canal Ronaldo F. Ramos.

README.md
=> Adicionando canal pedropacheco

README.md
=> adição do canal Renato Mota

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, README.md
=> Atualizando referencias do repositório 

README.md
=> Categoria Linux

README.md
=> Adicionando o canal Programe seu futuro.

.github/PULL_REQUEST_TEMPLATE.md
=> PR template typo
